spring:
  application:
    name: book-api
  datasource:
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: book-kafka-1:29092, book-kafka-2:29092, book-kafka-3:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: redis
      port: 6379
  elasticsearch:
    uris: http://elasticsearch:9200
server:
  port: 8082
secret: asdsaddsadsaadsdsaadssadasdsaddsadsadasdasdassaddsaasdsaddsa
management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  metrics:
    tags:
      application: "boock-api"
  endpoint:
    prometheus:
      enabled: true
