apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    isDefault: true
    version: 1
    editable: false
    uid: prometheus-datasource
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    orgId: 1
    isDefault: false
    version: 1
    editable: false
    uid: elasticsearch-datasource
    jsonData:
      esVersion: 8.11.0
      timeField: 'timestamp'
      index: "logs-api"
      maxConcurrentShardRequests: 5
      esQueryType: lucene
      logLevelField: 'level.keyword'
      logMessageField: 'message.keyword'