spring:
  application:
    name: keyword-consumer-service
  kafka:
    bootstrap-servers: book-kafka-1:29092,book-kafka-2:29092,book-kafka-3:29092
  data:
    redis:
      host: redis
      port: 6379